### ISSUE TITLE
Stories aren't unhiding even if we unhide them while we are in Hide Feed Mode

### ISSUE THREAD

**Issue by jash0803** [aymyo/antigram-extension#28]
If I unhide my feed, then my stories too are unhidden. And if only unhide stories then they still are hidden. Stories are only visible when we unhide feed.

**Comment by aymyo** [comment]
Hi! Thanks for notifying. Unfortunately I didn't have time until now to fix anything. And now a bunch of other thinks are broken. I'll try to fix it in the following weeks.
