### ISSUE TITLE
Support hiding reels

### ISSUE THREAD

**Issue by itay-sho** [aymyo/antigram-extension#34]
Hey, is there a way to hide reels and other "instagram suggestions" that are now part of the feed?

I tried playing with it by using javacsript like that:
a = document.querySelectorAll('article:has( a[href^=\\/reels])')
a.forEach((e) => {e.parentElement.removeChild(e)})

but it seems that it affects some of Instagram logic and breaks the page.
I also tried something less intrusive like changing the display to none but still it makes problems

I would be glad to add this feature in a pull request, any ideas how to bypass these problems?

**Comment by aymyo** [comment]
Hi @itay-sho. Firs of all sorry for the late response. Unfortunately I couldn't maintain this for several months,
What you propose is a very useful feature that many people have asked for. I think it's tricky. Tried similar approaches as that one without success.

As soon as I can dedicate a day to the extension, I'll focus on this issue

**Comment by itay-sho** [comment]
thanks for the update!

**Comment by PrasannaLanka** [comment]
Please do it; that would add a great feature and notify you when it's done. Reels are very addictive and kill our productivity.

**Comment by aymyo** [comment]
This is done now! @PrasannaLanka @itay-sho , sorry it took ages! I'll uplaod the new package to the Chrome Store and it should update at some point (they need to review it so it might take a few days)

Closing the issue
