### ISSUE TITLE
A Suggestion!!!

### ISSUE THREAD

**Issue by nerfelitewar** [aymyo/antigram-extension#35]
Hi, I loved your extension its pretty simple and very nice.

One small suggestion I'd like to give you is that please add option to **BLOCK REELS** as its pretty annoying. 
Its a simple issue but I will be glad if any such modification took place in this extention.

**Comment by aymyo** [comment]
Hi @nerfelitewar. Sorry for the late response: you are right, this is a good idea.

As soon as I have time, removing reels will be priority nº1

**Comment by aymyo** [comment]
I will close this issue since there is a similar one. Thanks a lot for raising it!
