### ISSUE TITLE
Suggestion, stop feed video audio from autoplaying even if the video post is hidden

### ISSUE THREAD

**Issue by ArdaOnen** [aymyo/antigram-extension#37]
As title suggests, if the first/displayed post in the feed is a video, it can start playing audio, and will then be hidden by antigram, while continuing audio, and you can't mute the video because the video is hidden by antigram. If you open your computer up and instagram is open at school or something, you'll be forced to immediately mute your laptop to avoid playing whatever the insta algo suggested for everyone in the room to hear.

**Comment by aymyo** [comment]
hi @ArdaOnen , thanks for pointing this out! I will try to include a fix in the next update
