### ISSUE TITLE
Toggles instead of checkboxes

### ISSUE THREAD

**Issue by olivierluethy** [aymyo/antigram-extension#47]
It's not a bug or an error, it's more of a request:
Is it possible to reimplement the toggles instead of the checkboxes?

**Comment by aymyo** [comment]
Hi Olivier! 
I decided to go simple to make the extension as light as possible and easier to mantain, so I try to use only native web elements now. Also, according to UX expertise, it's better to use checkboxes when the effect is not inmediate (check here! https://www.nngroup.com/articles/toggle-switch-guidelines/).

I'm closing this issue, but thanks a lot for you suggestion and trying to make the extension better ⭐

**Comment by olivierluethy** [comment]
No problem G. Thanks for your comment. 
Now I have learned something new.
Maybe you could make it so that the effect is immediate in the future. That would be awesome!
Have a good day and thanks again for your reply.
